# Generated by Django 4.2.7 on 2023-12-05 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='AItext',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='Text',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='URL',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
