# Generated by Django 4.2.7 on 2023-12-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_article_aitext_article_text_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='QualityArticle',
            field=models.BooleanField(default=False),
        ),
    ]
