# Generated by Django 4.2.7 on 2023-12-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='tempString', upload_to='pics'),
        ),
    ]
