# Generated by Django 4.2.7 on 2023-12-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='analysis',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='img',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='query',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='semquad',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
