# Generated by Django 4.2.7 on 2023-12-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_analysis_analysis_analysis_img_analysis_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='query',
            field=models.CharField(default='temp query', max_length=200),
            preserve_default=False,
        ),
    ]
