# Generated by Django 4.2.7 on 2023-12-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_article_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='URL',
            field=models.CharField(max_length=200),
        ),
    ]
