# Generated by Django 4.2.7 on 2023-12-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_alter_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='AItext',
            field=models.TextField(),
        ),
    ]
