# Generated by Django 4.2.7 on 2023-12-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_alter_article_aitext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurftStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
