# Generated by Django 4.2.7 on 2023-12-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_surftstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
