# Generated by Django 4.2.7 on 2023-12-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_alter_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis',
            field=models.CharField(max_length=1000),
        ),
    ]
