# Generated by Django 4.2.7 on 2023-12-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_alter_analysis_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='img',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='query',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='URL',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='query',
            field=models.CharField(max_length=256),
        ),
    ]
